# Generated by Django 4.2.4 on 2024-06-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appiumng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('memo', models.TextField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appiumng.search')),
            ],
        ),
    ]
