# Generated by Django 4.2.4 on 2024-06-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiumng', '0002_searchresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '位置情報', 'verbose_name_plural': '位置情報'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'プロフィール数設定', 'verbose_name_plural': 'プロフィール数設定'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': '検索情報設定', 'verbose_name_plural': '検索情報設定'},
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'verbose_name': '検索結果', 'verbose_name_plural': '検索結果'},
        ),
        migrations.AlterModelOptions(
            name='useragent',
            options={'verbose_name': 'UA設定', 'verbose_name_plural': 'UA設定'},
        ),
        migrations.AddField(
            model_name='useragent',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
