# Generated by Django 4.2.4 on 2024-06-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appiumng', '0003_alter_location_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=200)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appiumng.profile')),
            ],
        ),
    ]
