# Generated by Django 4.2.4 on 2024-06-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appiumng', '0007_search_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appiumng.device'),
        ),
    ]
