# Generated by Django 4.2.4 on 2024-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiumng', '0008_profile_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='profile_num',
            field=models.IntegerField(default=0),
        ),
    ]
