# Generated by Django 4.2.4 on 2024-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiumng', '0012_alter_device_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='system_port',
            field=models.IntegerField(default=8200),
        ),
    ]
