version: "3"
services:
  app:
    restart: always
    build:
      context: ./celery_app
    volumes:
      - ./celery_app:/usr/src/app
    depends_on:
      - db
      - redis
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: db
      DJANGO_DB_USER: docker
      DJANGO_DB_PASSWORD: docker
    command: |
      sh -c "python /usr/src/app/manage.py migrate && python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000

  db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: local_root_password
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql 
      
  redis:
    image: redis:latest
    restart: always
    tty: true
    ports:
      - 6379:6379

  celery:
    container_name: celery
    tty: true
    build:
      context: ./celery_app
    volumes:
      - ./celery_app:/usr/src/app
    working_dir: /usr/src/app
    command: celery -A config worker -l info
    depends_on:
      - app
      - redis

  beat:
    container_name: beat
    tty: true
    build:
      context: ./celery_app
    volumes:
      - ./celery_app:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "sleep 5 && celery -A config beat -l info"
    depends_on:
      - app
      - db
      - redis

volumes:
  db_data: